Improve formatting ux
dnnrly/httpref pull request #49
Opened 2024-10-25 13:51 UTC by Erfanm83

Hi @dnnrly,

As part of Hacktoberfest, I've made the following improvements based on the discussion in issue #40 (Additional formatting):

- Added borders to the description section to enhance readability.
- Changed the status and summary section to a status bar using the `lipgloss` package.
- Fixed failing tests caused by the UX changes.

Please let me know if there's any additional feedback or suggestions.

#40 
Thanks,
@Erfanm83

2024-10-25 21:50 UTC, dnnrly approved these changes

2024-10-25 21:50 UTC, dnnrly commented on httpref_test.go
> +		t.Errorf("Expected %v, but got %v", expected, actual)
Can we use `assert.Equal` here?

2024-10-25 21:50 UTC, dnnrly commented on view.go
> +	// glamour.DarkStyleConfig.Document.BackgroundColor = &backgroundColor
Please can this commented out code be removed?

2024-10-25 21:53 UTC, dnnrly commented
This is a great addition to `httpref`! Only some small amendments requested but otherwise a solid contribution. I might raise an issue with some additional work - but feel free to boost your Hacktoberfest PRs if you're up for it.

2024-10-25 21:54 UTC, dnnrly requested changes
Small changes required.

2024-10-27 09:46 UTC, Erfanm83 reviewed
Hi I have updated the code based on your reviews
Thanks for reveiwing if you had more of that let me know

2024-10-27 09:50 UTC, dnnrly approved these changes

2024-10-27 09:50 UTC, merged

2024-10-27 09:51 UTC, dnnrly commented
Thank you for your contribution! As is traditional for me, please let me know you Twitter username (if you have one) for me to start following you.

2024-10-27 09:56 UTC, Erfanm83 commented
Thanks @dnnrly for meging my updates!
I will be so glad if you want more changes to this project 
It looks like there is an issue of panic usage throughout the code, I want to fix that bug anyway

2024-10-27 12:09 UTC, Erfanm83 commented
> Thank you for your contribution! As is traditional for me, please let me know you Twitter username (if you have one) for me to start following you.

No I hadn't Twitter(X) Account . But I Created one with this username : @Erfanm_2004
I Will add my Twitter Profile on my Github Account soon .